In [1]:
import pandas as pd
from pathlib import Path

In [2]:
raw_path = Path("../data/raw/max_temp")

grd_files = sorted(raw_path.glob("*.GRD"))

print("IMD GRD files found:", len(grd_files))

for file in grd_files:
    print(file.name)

IMD GRD files found: 10
Maxtemp_MaxT_2015.GRD
Maxtemp_MaxT_2016.GRD
Maxtemp_MaxT_2017.GRD
Maxtemp_MaxT_2018.GRD
Maxtemp_MaxT_2019.GRD
Maxtemp_MaxT_2020.GRD
Maxtemp_MaxT_2021.GRD
Maxtemp_MaxT_2022.GRD
Maxtemp_MaxT_2023.GRD
Maxtemp_MaxT_2024.GRD

In [3]:
processed_file = Path(
    "../data/processed/maharashtra_max_temp_2015_2024.csv"
)

climate_df = pd.read_csv(processed_file)

print("Processed Maharashtra climate dataset loaded.")
print("Shape:", climate_df.shape)

Processed Maharashtra climate dataset loaded.
Shape: (94978, 4)

In [4]:
climate_df.head(10)

         date   lat   lon  max_temp_C
0  2015-01-01  16.5  73.5   27.577892
1  2015-01-01  17.5  73.5   25.906654
2  2015-01-01  17.5  74.5   25.796259
3  2015-01-01  17.5  75.5   26.639208
4  2015-01-01  18.5  73.5   25.075478
5  2015-01-01  18.5  74.5   24.909271
6  2015-01-01  18.5  75.5   24.916723
7  2015-01-01  18.5  76.5   26.742674
8  2015-01-01  18.5  77.5   26.959831
9  2015-01-01  19.5  73.5   24.861156

In [5]:
print("Number of observations:", len(climate_df))
print("Columns:", climate_df.columns.tolist())

print("\nMissing values:")
print(climate_df.isnull().sum())

Number of observations: 94978
Columns: ['date', 'lat', 'lon', 'max_temp_C']

Missing values:
date          0
lat           0
lon           0
max_temp_C    0
dtype: int64

In [8]:
years = [file.stem.split("_")[-1] for file in grd_files]

print("Available years:")
print(years)

Available years:
['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [9]:
sample_file = grd_files[0]

print("Sample IMD file:")
print(sample_file)
print("File size:", sample_file.stat().st_size, "bytes")

Sample IMD file:
..\data\raw\max_temp\Maxtemp_MaxT_2015.GRD
File size: 1403060 bytes

In [10]:
processed_path = Path(
    "../data/processed/maharashtra_max_temp_2015_2024.csv"
)

climate_df = pd.read_csv(processed_path)

print("Processed climate dataset loaded.")
print("Shape:", climate_df.shape)

Processed climate dataset loaded.
Shape: (94978, 4)

In [11]:
climate_df.head()

         date   lat   lon  max_temp_C
0  2015-01-01  16.5  73.5   27.577892
1  2015-01-01  17.5  73.5   25.906654
2  2015-01-01  17.5  74.5   25.796259
3  2015-01-01  17.5  75.5   26.639208
4  2015-01-01  18.5  73.5   25.075478

In [12]:
print("Total observations:", len(climate_df))

print("\nMissing values:")
print(climate_df.isnull().sum())

Total observations: 94978

Missing values:
date          0
lat           0
lon           0
max_temp_C    0
dtype: int64

In [13]:
print("Processing Summary")
print("------------------")
print("Region: Maharashtra")
print("Climate variable: Maximum Daily Temperature")
print("Period: 2015–2024")
print("Spatial resolution: 1° × 1°")
print("Processed observations:", len(climate_df))

Processing Summary
------------------
Region: Maharashtra
Climate variable: Maximum Daily Temperature
Period: 2015–2024
Spatial resolution: 1° × 1°
Processed observations: 94978

In [14]:
from pathlib import Path

raw_files = sorted(Path("../data/raw/max_temp").glob("*.GRD"))
processed_file = Path(
    "../data/processed/maharashtra_max_temp_2015_2024.csv"
)

print("RAW IMD DATA")
print("-----------")

for f in raw_files:
    print(f"{f.name} | {f.stat().st_size:,} bytes")

print("\nPROCESSED DATA")
print("--------------")
print(processed_file.name)
print(f"Size: {processed_file.stat().st_size:,} bytes")

RAW IMD DATA
-----------
Maxtemp_MaxT_2015.GRD | 1,403,060 bytes
Maxtemp_MaxT_2016.GRD | 1,406,904 bytes
Maxtemp_MaxT_2017.GRD | 1,403,060 bytes
Maxtemp_MaxT_2018.GRD | 1,403,060 bytes
Maxtemp_MaxT_2019.GRD | 1,403,060 bytes
Maxtemp_MaxT_2020.GRD | 1,406,904 bytes
Maxtemp_MaxT_2021.GRD | 1,403,060 bytes
Maxtemp_MaxT_2022.GRD | 1,403,060 bytes
Maxtemp_MaxT_2023.GRD | 1,403,060 bytes
Maxtemp_MaxT_2024.GRD | 1,406,904 bytes

PROCESSED DATA
--------------
maharashtra_max_temp_2015_2024.csv
Size: 3,008,864 bytes

### Processing Methodology

The original IMD 1° × 1° maximum-temperature data is provided
as binary GRD files.

The processing workflow consists of:

1. Reading the IMD binary GRD data.
2. Decoding the temperature values.
3. Associating values with their spatial grid coordinates.
4. Filtering the grid locations corresponding to Maharashtra.
5. Converting the extracted observations into a structured
   tabular dataset.
6. Saving the processed climate data as CSV for further
   exploratory analysis and machine-learning applications.

In [15]:
climate_df = pd.read_csv(processed_file)

print("Final Maharashtra Climate Dataset")
print("----------------------------------")
print("Rows:", len(climate_df))
print("Columns:", climate_df.shape[1])

climate_df.head(10)

Final Maharashtra Climate Dataset
----------------------------------
Rows: 94978
Columns: 4

         date   lat   lon  max_temp_C
0  2015-01-01  16.5  73.5   27.577892
1  2015-01-01  17.5  73.5   25.906654
2  2015-01-01  17.5  74.5   25.796259
3  2015-01-01  17.5  75.5   26.639208
4  2015-01-01  18.5  73.5   25.075478
5  2015-01-01  18.5  74.5   24.909271
6  2015-01-01  18.5  75.5   24.916723
7  2015-01-01  18.5  76.5   26.742674
8  2015-01-01  18.5  77.5   26.959831
9  2015-01-01  19.5  73.5   24.861156

In [16]:
print("Final dataset columns:")
print(climate_df.columns.tolist())

print("\nData types:")
print(climate_df.dtypes)

Final dataset columns:
['date', 'lat', 'lon', 'max_temp_C']

Data types:
date              str
lat           float64
lon           float64
max_temp_C    float64
dtype: object